# docker-compose.yml
services:
  my-next-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_STOMP_URL: ws://195.181.41.139/ws
        NEXT_PUBLIC_API_URL: https://195.181.41.139/api/
        NEXT_PUBLIC_IMAGE_URL: https://195.181.41.139/storage/
        NEXT_PUBLIC_BASE_URL: https://195.181.41.139/
        NEXT_PUBLIC_COOKIE_DOMAIN: 195.181.41.139
    image: my-next-app
    container_name: my-next-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped